config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  devise_for :users,
              path: '',
              path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :users, only: [:show]
  resources :rooms,except:[:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos,only:[:create,:destroy]
    resources :reservations,only:[:create]
  end

  resources :guest_reviews, only:[:create,:destroy]
  resources :host_reviews, only:[:create,:destroy]

  get '/your_trips'=>'reservations#your_trips'
  get '/your_reservations'=>'reservations#your_reservations'

  get 'search' => 'pages#search'
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :photos
  has_many :reservations

  has_many :guest_reviews


  geocoded_by :address
  after_validation :geocode,if: :address_changed?

  validates :home_type,presence: true
  validates :room_type,presence: true
  validates :accommodate,presence: true
  validates :bed_room,presence: true
  validates :bath_room,presence: true

  def cover_photo(size)
    if self.photos.length > 0
      self.photos[0].image.url(size)
    else
      "blank.jpg"
    end
  end

  def average_rating
    guest_reviews.count==0 ? 0:guest_reviews.average(:star).round(2).to_i

  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room,except: [:index,:new,:create]
  before_action :authenticate_user!,except:[:show]
  before_action :is_authorised,only:[:listing,:pricing,:description,:photo_upload,:amenities,:location,:update]

  def index
    @rooms = current_user.rooms
  end

  def new
    @room=current_user.rooms.build
  end

  def create
    @room=current_user.rooms.build(room_params)
    if @room.save
      redirect_to listing_room_path(@room),notice: "保存しました..."
    else
      flash[:alert]="入力に誤りがあります"
      render :new
    end
  end

  def show
    @photos=@room.photos
    @guest_reviews=@room.guest_reviews
  end

  def listing
  end

  def pricing
  end

  def description
  end

  def photo_upload
    @photos=@room.photos
  end

  def amenities
  end

  def location
  end

  def update

    new_params=room_params
    new_params=room_params.merge(active: true) if is_ready_room

    if @room.update(new_params)
      flash[:notice]="保存しました..."
    else
      flash[:alert]="入力に誤りがあります..."
    end
    redirect_back(fallback_location: request.referer)
  end

  #予約
  def preload
    today = Date.today
    reservations = @room.reservations.where("start_date >= ? OR end_date >= ?", today, today)

    render json: reservations
  end

  def preview
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])

    output = {
      conflict: is_conflict(start_date, end_date, @room)
    }

    render json: output
  end

  private

    def is_conflict(start_date, end_date, room)
      check = room.reservations.where("? < start_date AND end_date < ?", start_date, end_date)
      check.size > 0? true : false
    end

    def set_room
      @room=Room.find(params[:id])
    end

    def is_authorised
      redirect_to root_path,alert: "許可されていないページです" unless current_user.id == @room.user_id
    end

    def is_ready_room
      !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank?

    end

    def room_params
      params.require(:room).permit(:home_type,:room_type,:accommodate,:bed_room,:bath_room,:listing_name,:summary,:address,:is_tv,:is_kitchen,:is_air,:is_heating,:is_internet,:price,:active)
    end
end

app/helpers/room_helper.rb
module RoomHelper
end

app/views/rooms/_room_menu.html.erb
<ul class="sidebar-list">
  <li class="sidebar-item">
    <%= link_to "リスト",listing_room_path,class: "sidebar-link active"%>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "お金",pricing_room_path,class: "sidebar-link active"%>
    <% if !@room.price.blank?%>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "概要",description_room_path,class: "sidebar-link active"%>
    <% if !@room.listing_name.blank?%>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "フォト",photo_upload_room_path,class: "sidebar-link active"%>
    <% if !@room.photos.blank?%>
      <span id="photo_check" class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "アメニティー",amenities_room_path,class: "sidebar-link active"%>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "ロケーション",location_room_path,class: "sidebar-link active"%>
    <% if !@room.address.blank?%>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
</ul>

<hr/>

<% is_ready = !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank?%>

<%= form_for @room do |f|%>
 <%=f.hidden_field :active, value: true %>
 <%=f.submit "作成",id:"publish_button",class:"btn btn-normal btn-block" ,disabled: !is_ready%>
<% end %>

app/views/rooms/amenities.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu'%>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        アメニティー
      </div>

      <div class="panel-body">
        <div class="container">
          <%=form_for @room do |f| %>

          <div class="row form-group">
            <div class="col-md-4">
              <%=f.check_box :is_tv %>テレビ
            </div>
            <div class="col-md-4">
              <%=f.check_box :is_kitchen %>キッチン
            </div>
            <div class="col-md-4">
              <%=f.check_box :is_internet %>インターネット
            </div>
          </div>

          <div class="row form-group">
            <div class="col-md-4">
              <%=f.check_box :is_heating %>暖房
            </div>
            <div class="col-md-4">
              <%=f.check_box :is_air %>エアコン
            </div>
          </div>
          <br/><br/>

          <div class="text-center">
            <%=f.submit "保存",class:"btn btn-form" %>
          </div>

          <% end %>

        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/create.html.erb
<h1>Room#create</h1>
<p>Find me in app/views/room/create.html.erb</p>

app/views/rooms/description.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu'%>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        概要
      </div>

      <div class="panel-body">
        <div class="container">
          <%=form_for @room do |f| %>

            <div class="row">
              <div class="form-group">
                <label>リスティングネーム</label>
                <%=f.text_field :listing_name,placeholder:"リスティングネームを入力",class:"form-control" ,required:true %>
              </div>
            </div>

            <div class="row">
              <div class="form-group">
                <label>要約</label>
                <%=f.text_area :summary,rows:5,placeholder:"あなたの家の説明",class:"form-control" ,required:true %>
              </div>
            </div>

            <div class="text-center">
              <%=f.submit "保存",class:"btn btn-form" %>
            </div>


          <% end %>

        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "あなたのお部屋", rooms_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%=link_to "予約",your_reservations_path,class:"sidebar-link " %></li>
      <li class="sidebar-item"><%=link_to "あなたの旅行",your_trips_path,class:"sidebar-link " %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        リスティング
      </div>
      <div class="panel-body">

        <% @rooms.each do |room|%>
          <div class="row">
            <div class="col-md-2">
              <%=image_tag room.cover_photo(:thumb) %>
            </div>
            <div class="col-md-7">
              <h4><%=room.listing_name %></h4>
            </div>
            <div class="col-md-3 right">
              <%=link_to "アップデート",listing_room_path(room),class:"btn btn-form" %>
            </div>
          </div>
          <hr/>
        <% end%>

      </div>
    </div>
  </div>
</div>

app/views/rooms/listing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        リスト
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>

            <div class="row">

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>お家のタイプ</label>
                  <%= f.select :home_type, [["アパート/マンション", "Apartment"], ["一軒家", "House"], ["ベットと朝食付き", "Bed & Breakfast"]],
                                id: "home_type", prompt: "選択", class: "form-control" %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>お部屋のタイプ</label>
                  <%= f.select :room_type, [["まるまる貸し切り", "Entire"], ["個室", "Private"], ["シェアルーム", "Shared"]],
                                id: "room_type", prompt: "選択", class: "form-control" %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>人数</label>
                  <%= f.select :accommodate, [["1人", 1], ["2人", 2], ["3人", 3], ["4人以上", 4]],
                                id: "accommodate", prompt: "選択", class: "form-control" %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>ベットルーム</label>
                  <%= f.select :bed_room, [["1部屋", 1], ["2部屋", 2], ["3部屋", 3], ["4部屋以上", 4]],
                                id: "bed_room", prompt: "選択", class: "form-control" %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>バスルーム</label>
                  <%= f.select :bath_room, [["1個", 1], ["2個", 2], ["3個", 3], ["4個以上", 4]],
                                id: "bath_rooms", prompt: "選択", class: "form-control" %>
                </div>
              </div>

            </div>

            <div><%= f.submit "保存", class: "btn btn-normal" %></div>

          <% end %>

        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/location.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        建物がある場所
      </div>

      <div class="panel-body">
        <div class="container">
          <%=form_for @room do |f| %>

            <div class="row">
              <div class="form-group">
                <label>住所</label>
                <%=f.text_field :address,placeholder:"郵便番号を入力",class:"form-control",required:true  %>
              </div>
            </div>

            <div class="text-center">
              <%=f.submit "Save",class:"btn btn-form" %>
            </div>


          <% end %>

        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    お部屋を作成しよう！
  </div>
  <div class="panel-body">
    <div class="container">

      <%= form_for @room do |f| %>

        <div class="row">

          <div class="col-md-4 select">
            <div class="form-group">
              <label>お家のタイプ</label>
              <%= f.select :home_type, [["アパート/マンション", "Apartment"], ["一軒家", "House"], ["ベットと朝食付き", "Bed & Breakfast"]],
                            id: "home_type", prompt: "選択", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>お部屋のタイプ</label>
              <%= f.select :room_type, [["まるまる貸し切り", "Entire"], ["個室", "Private"], ["シェアルーム", "Shared"]],
                            id: "room_type", prompt: "選択", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>人数</label>
              <%= f.select :accommodate, [["1人", 1], ["2人", 2], ["3人", 3], ["4人以上", 4]],
                            id: "accommodate", prompt: "選択", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>ベットルーム</label>
              <%= f.select :bed_room, [["1部屋", 1], ["2部屋", 2], ["3部屋", 3], ["4部屋以上", 4]],
                            id: "bed_room", prompt: "選択", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>トイレ</label>
              <%= f.select :bath_room, [["1個", 1], ["2個", 2], ["3個", 3], ["4個以上", 4]],
                            id: "bath_rooms", prompt: "選択", class: "form-control" %>
            </div>
          </div>

        </div>

        <div><%= f.submit "作成！", class: "btn btn-normal" %></div>

      <% end %>

    </div>
  </div>
</div>

app/views/rooms/photo_upload.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Photo
      </div>

      <div class="panel-body">
        <div class="container">
          <div class="row">
            <div class="col-md-offset-3 col-md-6">
              <!--写真アップロード -->
              <%=form_for @room, url:room_photos_path(@room),method:'post',html:{multipart: true} do |f| %>
                <div class="row">
                  <div class="form-group">
                    <span class="btn btn-default btn-file text-babu">
                      <i class="fa fa-cloud-upload" aria-hidden="true"></i>　写真を選ぶ
                      <%=file_field_tag "images[]",type: :file,multiple:true %>
                    </span>
                  </div>
                </div>

                <div class="text-center">
                  <%= f.submit "写真を追加",class:"btn btn-form" %>
                </div>
              <% end %>
            </div>
          </div>
          <div id="photos"><%= render 'photos/photos_list' %></div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/pricing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu'%>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        金額
      </div>

      <div class="panel-body">
        <div class="container">
          <%=form_for @room do |f| %>

            <div class="row">
              <div class="form-group">
                <label>金額</label>
                <%=f.text_field :price,placeholder:" （例）¥1000",class:"form-control",required:true  %>
              </div>
            </div>

            <div class="text-center">
              <%=f.submit "保存",class:"btn btn-form" %>
            </div>


          <% end %>

        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<!-- 画像 -->
<div class="row">
  <div class="col-md-12">
    <%=image_tag @room.cover_photo(nil),width:"100%" %>
  </div>
</div>
<br/>

<div class="row">

  <!-- 左のパネル-->
  <div class="col-md-8">

    <!-- リスティングネーム-->
    <div class="row">
      <div class="col-md-8">
        <h1><%=@room.listing_name %></h1>
        <%= @room.address %>
      </div>

      <div class="col-md-4 text-center">
        <%= image_tag avatar_url(@room.user),class:"img-circle avatar-large" %><br/><br/>
        <%= @room.user.fullname %>

      </div>

    </div>
    <hr/>

    <!-- 部屋の情報-->
    <div class="row text-babu">
      <div class="row text-center row-space-1">
        <div class="col-md-3">
          <i class="fa fa-home fa-2x"></i>
        </div>
        <div class="col-md-3">
          <i class="fa fa-user-circle-o fa-2x"></i>
        </div>
        <div class="col-md-3">
          <i class="fa fa-bed fa-2x"></i>
        </div>
        <div class="col-md-3">
          <i class="fa fa-bath fa-2x"></i>
        </div>
      </div>

      <div class="row text-center">
        <div class="col-md-3"><%= @room.home_type %></div>
        <div class="col-md-3"><%=pluralize(@room.accommodate,"Guest") %></div>
        <div class="col-md-3"><%=pluralize(@room.bed_room,"Bedroom") %></div>
        <div class="col-md-3"><%=pluralize(@room.bath_room,"Bathroom") %></div>
      </div>


    </div>
    <hr/>

    <!-- about-->
    <div class="row">
      <div class="col-md-12">
        <h3>このお部屋について</h3>
        <p><%=@room.summary %></p>
      </div>

    </div>
    <hr/>

    <!-- アメニティー-->
    <div class="row">
      <div class="col-md-3">
        <h4>Amenities</h4>
      </div>
      <div class="col-md-9">
        <div class="row">
          <div class="col-md-6">
            <ul class="amenities">
              <li　class="<%='text-line-through' if !@room.is_tv %> ">テレビ</li>
              <li  class="<%='text-line-through' if !@room.is_kitchen %> ">キッチン</li>
              <li  class="<%='text-line-through' if !@room.is_internet %> ">インターネット</li>
            </ul>
          </div>
          <div class="col-md-6">
            <ul class="amenities">
              <li  class="<%='text-line-through' if !@room.is_heating %> ">暖房</li>
              <li  class="<%='text-line-through' if !@room.is_air %> ">エアコン</li>
            </ul>
          </div>
        </div>
      </div>

    </div>
    <hr/>

    <!-- carousel-->
    <div class="row">

      <% if @photos.length >0 %>


      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <% @photos.each do |photo|%>
              <li data-target="#myCarousel" data-slide-to="<%=photo.id %>" ></li>
          <% end %>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
          <% @photos.each do |photo|%>
              <div class="item <%='active' if photo.id==@photos[0].id %>">
                <%=image_tag photo.image.url()  %>
              </div>
          <% end %>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

      <% end %>

    </div>
    <hr/>

    <!--レビュー-->
    <div class="row">
      <div class="col-md-12">
        <h3>
          <%=pluralize(@guest_reviews.count,"Review") %>
          <span id="average_rating"></span>
        </h3>
        <div class="container">
          <div><%=render "reviews/guest_list" %></div>
        </div>
      </div>
    </div>
    <br/>
    <br/>






    <!--Google マップ-->
    <div class="row">

      <div id="map" style="width: 100%; height: 400px"></div>

      <script src=https://maps.googleapis.com/maps/api/js?key=AIzaSyBs_NhV96CU6jZ05aaak1WCh-PyEe3UZa0&callback=initMap></script>
      <script>
        function initialize() {
          var location = {lat: <%= @room.latitude %>, lng: <%= @room.longitude %>};
          var map = new google.maps.Map(document.getElementById('map'), {
            center: location,
            zoom: 14
          });

          var marker = new google.maps.Marker({
            position: location,
            map: map
          });

          var infoWindow = new google.maps.InfoWindow({
            content: '<div id="content"><%= image_tag @room.cover_photo(:medium) %></div>'
          });

          infoWindow.open(map, marker)
        }

          google.maps.event.addDomListener(window, 'load', initialize);
      </script>

    </div>
    <hr/>

    <!--近くのお部屋-->
    <div class="row">
      <h3>近くの部屋</h3>
      <% for room in @room.nearbys(10) %>
        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-heading preview">
              <%=image_tag room.cover_photo(:medium) %>
            </div>
            <div class="panel-body">
              <%=link_to room.listing_name,room  %><br/>
              <%=room.distance.round(2) %> km離れています
            </div>
          </div>
        </div>
      <% end %>

    </div>

  </div>

  <!-- 右のパネル-->
  <div class="col-md-4">
    <!--予約フォーム-->
    <%=render 'reservations/form' %>

  </div>
</div>

<script>
  $('#average_rating').raty({
    path: '/assets',
    readOnly: true,
    score: <%=@room.average_rating %>
  });
</script>

app/views/rooms/update.html.erb
<h1>Room#update</h1>
<p>Find me in app/views/room/update.html.erb</p>